### ISSUE TITLE
GRAD MinUI is showing up in S.O.G. Prairie Fire Main Menu

### ISSUE THREAD

**Issue by y0014984** [gruppe-adler/grad_minui#19]
As you can see in the screenshot, GRAD MinUI is showing up in the main menu of the new Creator DLC S.O.G. Prairie Fire. I'm not sure if it shows up directly after game start or only if you leave a mission and go back to the main menu. GRAD MinUI disappears after a short amount of time by fading out. This time interval seems to be longer than the defined value in the CBA Settings. I think it is because the loaded mission in the background of the main menu is running on lower speed (slow motion effect). But I haven't investigated this any further.

![](https://imgur.com/oiEnqXk.png)

**Comment by y0014984** [comment]
To reproduce, you need to start Arma 3 without the two startup paramters -world=empty and -skipIntro

**Comment by y0014984** [comment]
Perhaps this is related to this comment: https://github.com/diwako/diwako_dui/issues/197#issuecomment-861880898

**Comment by DerZade** [comment]
Considering we’re not using CBA probably not, but I’ll take a look at their solution. 😇
