### ISSUE TITLE
Missing base class Attributes & UI broken as of latest commit

### ISSUE THREAD

**Issue by LarsAsprah** [gruppe-adler/grad_minui#25]
Hi-ho. Tested the latest commit on my machine, and experienced several hiccups:

First issue I encountered was a missing base class Attributes, line 18 message on launch. After a inserting a class Attributes; to the start of the file it started up without issue, and the hold action now indeed shows up as advertised, but now when I load a save game ace ui elements such as ammo count, weapon temperature and the like are no longer visible, but work fine on mission start. 

Last issue is that the new infantry speed indicator seems to break this, at least I think so, since I have to restart a scenario to have the vanilla stance indicator be invisible; otherwise it's only the new speed and medical indicators that are visible the first time a mission is launched.

As always, thank you for your hard work, and I hope I could be of help to this nifty up-and-coming mod with this feedback.

**Comment by DerZade** [comment]
Hey,
glad you're still around testing my stuff :D Always much appreciated 

---

> First issue I encountered was a missing base class Attributes, line 18 message on launch After a inserting a class Attributes; to the start of the file it started up without issue

I didn't have any error messages, when I played on monday. Where exactly did you add a class to fix the issue? 🤔

---

>  but now when I load a save game ace ui elements such as ammo count, weapon temperature and the like are no longer visible, but work fine on mission start.

Are you sure that this is a issue related to grad_minui? I don't touch those at all, especially the save game is confusing me.

---

> Last issue is that the new infantry speed indicator seems to break this, at least I think so, since I have to restart a scenario to have the vanilla stance indicator be invisible; otherwise it's only the new speed and medical indicators that are visible the first time a mission is launched.

I'm aware of the infantry speed indicator. My goal is to make it invisible like the rest of the stance indicator is. (see #24) 
I don't know what you mean by "medical indicators" tho. Can you elaborate?

**Comment by LarsAsprah** [comment]
Sorry for the slow reply, was in-game. 

---------------------------
Arma 3
---------------------------
File x\grad_minui\addons\defaultactionicon\RscTitles.hpp, line 17: /RscTitles/grad_minui_holdAction_progress/controls/txt.Attributes: Undefined base class 'Attributes'
---------------------------
OK   
---------------------------

I got this error message.

**Comment by LarsAsprah** [comment]
Update: 
Turns out the other issues were the fault of another mod which passed me by. Completely my fault, sorry!
The inheritance issue is still open, though.

**Comment by DerZade** [comment]
RPT Error should be fixed. 
I created #26 for the medical indicators :D 

So I guess everything in this ticket was addressed?

**Comment by LarsAsprah** [comment]
Affirmative. Can confirm that it works with no issue now, thanks!

**Comment by DerZade** [comment]
Thanks for reporting the issue 🤗
